### ISSUE TITLE
Versioning issue

### ISSUE THREAD

**Issue by Abastro** [TeamKuiper/Redoxiation#1]
It seems like your versioning is far from semantic versioning, so there would be problem in version sorting.
I suggest it this way:

0.1.5-a1:
0: Major version. This means dev.
1: Minecraft version (1 means first mc version)
5: Minor version. Change in a minecraft version, without bugfixes.
a: This means alpha. Slightly , but gives better readability. This can still be sorted.
1: Bugfixes; Assume no bugfix have been done, so this is set to 1.

**Comment by Abastro** [comment]
- Please change build.gradle to patch version of main mod java file.
  Believe me, it saves time to change all the versions.

**Comment by H2ewis** [comment]
버전 이름 붙이는건 지금 대충 해둔거라 그래요. 시간 되면 수정하죠. build.gradle 수정하는건 알고 있습니다.

**Comment by Abastro** [comment]
Please change it before a release. It could be vast barrier against you when its too late.

**Comment by H2ewis** [comment]
ㅇㅇ 오늘 이따가 할거에요

**Comment by Abastro** [comment]
Thanks!
