### ISSUE TITLE
Release on 1.9.4

### ISSUE THREAD

**Issue by Abastro** [TeamKuiper/Redoxiation#3]
It seems like that 1.9.4 will be major version like 1.7.10. (Due to Few changes from 1.8.9 & Stability)
Also there was move of Multipart teams to put Multipart into Forge itself.

So, what do you think about release on 1.9.4?

**Comment by H2ewis** [comment]
언젠가 옮겨야겠지요.

**Comment by Kuiprux** [comment]
두가지 생각이 드네요.
1. 1710버전을 완성한 다음에 옮겨야 한다고 생각합니다. 아직 1710을 사용하는 유저도 꽤 있고, 모드팩도 많기 때문이죠. 만약 다 완성되기 전에 유저들이 다른 버전으로 옮긴다면, 그때 옮기면 될 것 같습니다.
2. 다 완성되려면 시간이 걸릴 테고, 그 동안 유저들이 다른 버전으로 옮길 수도 있습니다. 미리 버전을 올리고 개발하면, 유저들이 이 버전으로 옮길 때까지 시간적 여유가 있습니다. 그러므로 미리 버전을 올리고 개발하는 게 낫다고 생각합니다.

으으.. 의견이 상반되는군요.
다른 분들의 생각은 어떠십니까

**Comment by Abastro** [comment]
It shouldn't be any issue.
- There is many bugs in forge itself remaining in 1.7.10, and you won't get any support about it. It could be big problem for this big mod.
- Also it seems that this mod needs much time to be developed, which makes the main point redundant.
- Lots of time passed, quite many players has already moved to 1.9~1.10, and most of the major mods under 1.8 are planned to be updated in few months, which will have the remaining modpacks be updated, followed by remaining players.
- Moreover, 1.11 is coming! So 1.7.10 will be already 3 major versions off! For mods, It's quite late already. (The mod update phase is much faster than players, since players could update when mods are updated)
- Do note that porting from 1.7.10 to 1.8+ is really challenging work, while porting from 1.8+ is too easy compared to that.

**Comment by Kuiprux** [comment]
으음.. 그럼 올려놓고 개발하는 게 낫겠네요.
api는 당연히 달라지겠죠..?

**Comment by malangbalam** [comment]
2년간 이슈 갱신이 없으므로 닫습니다.
필요시 reopen

**Comment by Abastro** [comment]
Oh, it's alive?

**Comment by malangbalam** [comment]
례~~~신분세탁하고 잘살고잇습니다~~
